# Generated by Django 5.2.4 on 2025-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='careerStage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='cityName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='countryCode',
            field=models.CharField(default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='ipi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='isni',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='artists', to='soundcharts.genre'),
        ),
    ]
