# Generated by Django 5.2.5 on 2025-08-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0002_genre_artist_biography_artist_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('time_zone', models.CharField(max_length=255)),
                ('reach', models.IntegerField()),
                ('first_aired_at', models.DateTimeField()),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='country_code',
            field=models.CharField(default='IT', max_length=2),
        ),
        migrations.AddField(
            model_name='chart',
            name='frequency',
            field=models.CharField(default='weekly', max_length=100),
        ),
        migrations.AddField(
            model_name='chart',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundcharts.platform'),
        ),
        migrations.AddField(
            model_name='chart',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='type',
            field=models.CharField(default='song', max_length=100),
        ),
        migrations.AddField(
            model_name='chart',
            name='web_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
