# Generated by Django 5.2.5 on 2025-08-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0003_radio_chart_country_code_chart_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='uuid',
        ),
        migrations.CreateModel(
            name='ChartRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_date', models.DateTimeField(help_text='Date when this ranking was published')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When this ranking was fetched from API')),
                ('total_entries', models.IntegerField(default=0, help_text='Total number of entries in this ranking')),
                ('chart_period', models.CharField(blank=True, help_text="Chart period (e.g., 'weekly', 'daily')", max_length=100)),
                ('chart_type', models.CharField(blank=True, help_text="Chart type (e.g., 'song', 'album')", max_length=100)),
                ('api_response_id', models.CharField(blank=True, help_text='API response identifier', max_length=255)),
                ('api_version', models.CharField(blank=True, help_text='API version used', max_length=50)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='soundcharts.chart')),
            ],
            options={
                'verbose_name': 'Chart Ranking',
                'verbose_name_plural': 'Chart Rankings',
                'ordering': ['-ranking_date'],
                'unique_together': {('chart', 'ranking_date')},
            },
        ),
        migrations.CreateModel(
            name='ChartRankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Current position in the chart')),
                ('previous_position', models.IntegerField(blank=True, help_text='Previous position (if available)', null=True)),
                ('position_change', models.IntegerField(blank=True, help_text='Position change from previous ranking', null=True)),
                ('weeks_on_chart', models.IntegerField(blank=True, help_text='Number of weeks on chart', null=True)),
                ('track_name', models.CharField(help_text='Name of the track', max_length=500)),
                ('track_uuid', models.CharField(blank=True, help_text='Soundcharts track UUID', max_length=255)),
                ('track_slug', models.CharField(blank=True, help_text='Soundcharts track slug', max_length=255)),
                ('artist_name', models.CharField(help_text='Name of the artist', max_length=500)),
                ('artist_uuid', models.CharField(blank=True, help_text='Soundcharts artist UUID', max_length=255)),
                ('artist_slug', models.CharField(blank=True, help_text='Soundcharts artist slug', max_length=255)),
                ('album_name', models.CharField(blank=True, help_text='Name of the album', max_length=500)),
                ('album_uuid', models.CharField(blank=True, help_text='Soundcharts album UUID', max_length=255)),
                ('album_slug', models.CharField(blank=True, help_text='Soundcharts album slug', max_length=255)),
                ('streams', models.BigIntegerField(blank=True, help_text='Stream count', null=True)),
                ('views', models.BigIntegerField(blank=True, help_text='View count', null=True)),
                ('sales', models.BigIntegerField(blank=True, help_text='Sales count', null=True)),
                ('airplay', models.IntegerField(blank=True, help_text='Airplay count', null=True)),
                ('isrc', models.CharField(blank=True, help_text='International Standard Recording Code', max_length=50)),
                ('label', models.CharField(blank=True, help_text='Record label', max_length=255)),
                ('genre', models.CharField(blank=True, help_text='Genre', max_length=255)),
                ('country_code', models.CharField(blank=True, help_text='Country code', max_length=2)),
                ('api_data', models.JSONField(default=dict, help_text='Raw API response data for this entry')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='soundcharts.chartranking')),
            ],
            options={
                'verbose_name': 'Chart Ranking Entry',
                'verbose_name_plural': 'Chart Ranking Entries',
                'ordering': ['position'],
                'unique_together': {('ranking', 'position')},
            },
        ),
    ]
