# Generated by Django 5.2.5 on 2025-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0004_remove_chart_uuid_chartranking_chartrankingentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chartranking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chartranking',
            constraint=models.UniqueConstraint(fields=('chart', 'ranking_date'), name='unique_chart_ranking_date'),
        ),
    ]
