# Generated by Django 5.2.5 on 2025-08-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0005_alter_chartranking_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='isrc',
        ),
    ]
