# Generated by Django 5.2.5 on 2025-08-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0006_remove_chartrankingentry_isrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartranking',
            name='api_response_id',
        ),
        migrations.RemoveField(
            model_name='chartranking',
            name='chart_period',
        ),
        migrations.RemoveField(
            model_name='chartranking',
            name='chart_type',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='airplay',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='album_slug',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='album_uuid',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='artist_slug',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='artist_uuid',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='label',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='track_name',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='track_slug',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='track_uuid',
        ),
        migrations.RemoveField(
            model_name='chartrankingentry',
            name='views',
        ),
        migrations.AddField(
            model_name='chartranking',
            name='chart_entries',
            field=models.ManyToManyField(related_name='rankings', to='soundcharts.chartrankingentry'),
        ),
        migrations.AddField(
            model_name='chartrankingentry',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='song_rankings', to='soundcharts.track'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='credit_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='image_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
