# Generated by Django 5.2.5 on 2025-08-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0007_remove_chartranking_api_response_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chartrankingentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chartranking',
            name='chart_entries',
        ),
        migrations.AlterField(
            model_name='track',
            name='credit_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='chartrankingentry',
            constraint=models.UniqueConstraint(fields=('ranking', 'position'), name='unique_ranking_position'),
        ),
    ]
