# Generated by Django 5.2.5 on 2025-08-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0008_alter_chartrankingentry_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='code',
            new_name='slug',
        ),
    ]
