# Generated by Django 5.2.5 on 2025-08-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0009_rename_code_platform_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartrankingentry',
            name='ranking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='soundcharts.chartranking'),
        ),
    ]
