# Generated by Django 5.2.5 on 2025-08-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0010_alter_chartrankingentry_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartrankingentry',
            name='ranking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='soundcharts.chartranking'),
            preserve_default=False,
        ),
    ]
