# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0011_alter_chartrankingentry_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartranking',
            name='chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='soundcharts.chart'),
        ),
        migrations.AlterField(
            model_name='chartrankingentry',
            name='ranking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='soundcharts.chartranking'),
        ),
    ]
