# Generated by Django 5.2.5 on 2025-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0013_metadatafetchtask_track_audience_fetched_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartRankingEntrySummary',
            fields=[
            ],
            options={
                'verbose_name': 'Chart Entry Summary',
                'verbose_name_plural': 'Chart Entries Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('soundcharts.chartrankingentry',),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, help_text='Primary genre', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, help_text='International Standard Recording Code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='label',
            field=models.CharField(blank=True, help_text='Record label', max_length=255, null=True),
        ),
    ]
