# Generated by Django 5.2.5 on 2025-09-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0014_chartrankingentrysummary_alter_track_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='audience_metric_name',
            field=models.CharField(default='Listeners', help_text="Name of the audience metric (e.g., 'Listeners', 'Followers')", max_length=100),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_identifier',
            field=models.CharField(blank=True, help_text="Platform-specific identifier (e.g., 'spotify', 'apple_music')", max_length=255),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('streaming', 'Streaming'), ('social', 'Social Media'), ('radio', 'Radio'), ('tv', 'TV'), ('other', 'Other')], default='streaming', help_text='Type of platform', max_length=50),
        ),
        migrations.CreateModel(
            name='TrackAudienceTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the audience measurement')),
                ('audience_value', models.BigIntegerField(help_text='Audience value for this date/platform')),
                ('platform_identifier', models.CharField(blank=True, help_text="Platform-specific identifier (e.g., '2Fxmhks0bxGSBdJ92vM42m')", max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('api_data', models.JSONField(default=dict, help_text='Raw API response data for this entry')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_timeseries', to='soundcharts.platform')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_timeseries', to='soundcharts.track')),
            ],
            options={
                'verbose_name': 'Track Audience Time Series',
                'verbose_name_plural': 'Track Audience Time Series',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['track', 'platform', 'date'], name='soundcharts_track_i_a83369_idx'), models.Index(fields=['date'], name='soundcharts_date_a28d75_idx'), models.Index(fields=['platform', 'date'], name='soundcharts_platfor_4460d6_idx')],
                'unique_together': {('track', 'platform', 'date')},
            },
        ),
    ]
