# Generated by Django 5.2.5 on 2025-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0015_platform_audience_metric_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('audience', 'Audience'), ('streaming', 'Streaming'), ('song_chart', 'Song Chart'), ('artist_chart', 'Artist Chart'), ('album_chart', 'Album Chart'), ('playlist', 'Playlist'), ('radio', 'Radio'), ('other', 'Other')], default='streaming', help_text='Type of platform', max_length=50),
        ),
    ]
