# Generated by Django 5.2.5 on 2025-09-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0016_alter_platform_platform_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='Optional genre description'),
        ),
        migrations.AddField(
            model_name='genre',
            name='level',
            field=models.IntegerField(default=0, help_text='Hierarchy level (0=root, 1=sub)'),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent genre (root genre). Null for root genres.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgenres', to='soundcharts.genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='', help_text='URL-friendly genre identifier', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='soundcharts_root',
            field=models.CharField(blank=True, help_text='Original root genre name from SoundCharts API', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Track genres', related_name='tracks', to='soundcharts.genre'),
        ),
        migrations.AddField(
            model_name='track',
            name='primary_genre',
            field=models.ForeignKey(blank=True, help_text='Primary genre for this track', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tracks', to='soundcharts.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text="Genre name (e.g., 'alternative', 'electronic')", max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='uuid',
            field=models.CharField(blank=True, help_text='SoundCharts genre UUID if available', max_length=255),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['parent', 'level'], name='soundcharts_parent__68ce09_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['slug'], name='soundcharts_slug_d22baa_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['soundcharts_root'], name='soundcharts_soundch_b3acff_idx'),
        ),
    ]
