# Generated by Django 5.2.5 on 2025-09-09 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0017_update_genre_model_hierarchical'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(blank=True, help_text='Track artists', related_name='tracks', to='soundcharts.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='primary_artist',
            field=models.ForeignKey(blank=True, help_text='Primary artist for this track', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tracks', to='soundcharts.artist'),
        ),
    ]
