# Generated by Django 5.2.5 on 2025-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0018_add_artist_relationships_to_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='acrcloud_id',
            field=models.CharField(blank=True, help_text='ACRCloud album identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='musicbrainz_id',
            field=models.CharField(blank=True, help_text='MusicBrainz album ID', max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='platform_ids',
            field=models.JSONField(blank=True, default=dict, help_text='Platform-specific album IDs'),
        ),
        migrations.AddField(
            model_name='artist',
            name='acrcloud_id',
            field=models.CharField(blank=True, help_text='ACRCloud artist identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='musicbrainz_id',
            field=models.CharField(blank=True, help_text='MusicBrainz artist ID', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='platform_ids',
            field=models.JSONField(blank=True, default=dict, help_text='Platform-specific artist IDs'),
        ),
        migrations.AddField(
            model_name='track',
            name='acrcloud_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='When ACRCloud analysis was performed', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='acrcloud_id',
            field=models.CharField(blank=True, help_text='ACRCloud track identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='acrcloud_score',
            field=models.IntegerField(blank=True, help_text='ACRCloud confidence score', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='musicbrainz_id',
            field=models.CharField(blank=True, help_text='MusicBrainz track ID', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='platform_ids',
            field=models.JSONField(blank=True, default=dict, help_text='Platform-specific track IDs'),
        ),
        migrations.AddField(
            model_name='track',
            name='upc',
            field=models.CharField(blank=True, help_text='Universal Product Code', max_length=255),
        ),
    ]
