# Generated by Django 5.2.5 on 2025-09-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0019_album_acrcloud_id_album_musicbrainz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
