# Generated by Django 5.2.5 on 2025-09-29 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0020_add_unique_constraint_to_platform_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sync schedule is active')),
                ('sync_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Interval')], help_text='How often to sync this chart', max_length=50)),
                ('custom_interval_hours', models.IntegerField(blank=True, help_text="Custom interval in hours (only used if sync_frequency is 'custom')", null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When this chart was last synced', null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, help_text='When this chart should be synced next', null=True)),
                ('total_executions', models.IntegerField(default=0, help_text='Total number of sync executions')),
                ('successful_executions', models.IntegerField(default=0, help_text='Number of successful sync executions')),
                ('failed_executions', models.IntegerField(default=0, help_text='Number of failed sync executions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(help_text='Chart to sync', on_delete=django.db.models.deletion.CASCADE, related_name='sync_schedules', to='soundcharts.chart')),
                ('created_by', models.ForeignKey(help_text='User who created this sync schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart Sync Schedule',
                'verbose_name_plural': 'Chart Sync Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartSyncExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of this execution', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When this execution started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this execution completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('rankings_created', models.IntegerField(default=0, help_text='Number of chart rankings created in this execution')),
                ('rankings_updated', models.IntegerField(default=0, help_text='Number of chart rankings updated in this execution')),
                ('tracks_created', models.IntegerField(default=0, help_text='Number of tracks created in this execution')),
                ('tracks_updated', models.IntegerField(default=0, help_text='Number of tracks updated in this execution')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for this execution', max_length=255)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retries allowed')),
                ('schedule', models.ForeignKey(help_text='The sync schedule this execution belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='soundcharts.chartsyncschedule')),
            ],
            options={
                'verbose_name': 'Chart Sync Execution',
                'verbose_name_plural': 'Chart Sync Executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chartsyncschedule',
            constraint=models.UniqueConstraint(fields=('chart',), name='unique_chart_sync_schedule'),
        ),
    ]
