# Generated by Django 5.2.5 on 2025-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0021_chartsyncschedule_chartsyncexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsyncschedule',
            name='fetch_track_metadata',
            field=models.BooleanField(default=True, help_text='Whether to fetch track metadata during chart sync'),
        ),
        migrations.AddField(
            model_name='chartsyncschedule',
            name='sync_historical_data',
            field=models.BooleanField(default=True, help_text='Whether to sync all historical data based on chart frequency'),
        ),
        migrations.AddField(
            model_name='chartsyncschedule',
            name='sync_immediately',
            field=models.BooleanField(default=False, help_text='Whether to start sync immediately when schedule is created'),
        ),
    ]
