# Generated by Django 5.2.5 on 2025-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0022_chartsyncschedule_fetch_track_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsyncexecution',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for this execution', max_length=255, null=True),
        ),
    ]
