# Generated by Django 5.2.5 on 2025-10-15 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0023_alter_chartsyncexecution_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='audience_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When audience data was last fetched', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='metadata_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When metadata was last fetched', null=True),
        ),
        migrations.CreateModel(
            name='ArtistAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_listeners', models.BigIntegerField(blank=True, help_text='Total number of listeners', null=True)),
                ('unique_listeners', models.BigIntegerField(blank=True, help_text='Unique listeners', null=True)),
                ('repeat_listeners', models.BigIntegerField(blank=True, help_text='Repeat listeners', null=True)),
                ('age_13_17', models.IntegerField(blank=True, help_text='Listeners aged 13-17', null=True)),
                ('age_18_24', models.IntegerField(blank=True, help_text='Listeners aged 18-24', null=True)),
                ('age_25_34', models.IntegerField(blank=True, help_text='Listeners aged 25-34', null=True)),
                ('age_35_44', models.IntegerField(blank=True, help_text='Listeners aged 35-44', null=True)),
                ('age_45_54', models.IntegerField(blank=True, help_text='Listeners aged 45-54', null=True)),
                ('age_45_59', models.IntegerField(blank=True, help_text='Listeners aged 45-59', null=True)),
                ('age_55_64', models.IntegerField(blank=True, help_text='Listeners aged 55-64', null=True)),
                ('age_60_150', models.IntegerField(blank=True, help_text='Listeners aged 60+', null=True)),
                ('age_65_plus', models.IntegerField(blank=True, help_text='Listeners aged 65+', null=True)),
                ('gender_male', models.IntegerField(blank=True, help_text='Male listeners percentage', null=True)),
                ('gender_female', models.IntegerField(blank=True, help_text='Female listeners percentage', null=True)),
                ('top_countries', models.JSONField(default=list, help_text='Top countries by listeners')),
                ('top_cities', models.JSONField(default=list, help_text='Top cities by listeners')),
                ('api_data', models.JSONField(default=dict, help_text='Raw API response data')),
                ('report_date', models.DateField(blank=True, help_text='Date of the audience report', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When this data was fetched')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_data', to='soundcharts.artist')),
                ('platform', models.ForeignKey(help_text='Platform for this audience data', on_delete=django.db.models.deletion.CASCADE, to='soundcharts.platform')),
            ],
            options={
                'verbose_name': 'Artist Audience',
                'verbose_name_plural': 'Artist Audiences',
                'ordering': ['-fetched_at'],
                'unique_together': {('artist', 'platform', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='ArtistAudienceTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the audience measurement')),
                ('audience_value', models.BigIntegerField(help_text='Audience value for this date/platform')),
                ('platform_identifier', models.CharField(blank=True, help_text="Platform-specific identifier (e.g., '06HL4z0CvFAxyc27GXpf02' for Taylor Swift)", max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('api_data', models.JSONField(default=dict, help_text='Raw API response data for this entry')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_timeseries', to='soundcharts.artist')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_audience_timeseries', to='soundcharts.platform')),
            ],
            options={
                'verbose_name': 'Artist Audience Time Series',
                'verbose_name_plural': 'Artist Audience Time Series',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['artist', 'platform', 'date'], name='soundcharts_artist__a990c4_idx'), models.Index(fields=['date'], name='soundcharts_date_2a73fa_idx'), models.Index(fields=['platform', 'date'], name='soundcharts_platfor_e24ced_idx')],
                'unique_together': {('artist', 'platform', 'date')},
            },
        ),
    ]
