# Generated by Django 5.2.5 on 2025-10-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcharts', '0024_artist_audience_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartrankingentry',
            name='entry_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Date when the track first entered this chart (from SoundCharts API)'
            ),
        ),
        migrations.AddField(
            model_name='chartrankingentry',
            name='exit_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Date when the track left this chart (calculated from last appearance)'
            ),
        ),
    ]
