# Generated by Django 5.2.5 on 2025-09-16 12:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACRCloudConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('bearer_token', models.CharField(max_length=500)),
                ('container_id', models.CharField(max_length=100)),
                ('identify_host', models.CharField(max_length=100)),
                ('identify_access_key', models.CharField(max_length=100)),
                ('identify_access_secret', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ACRCloud Configuration',
                'verbose_name_plural': 'ACRCloud Configurations',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('fingerprint', 'Fingerprint Analysis'), ('cover', 'Cover Detection'), ('lyrics', 'Lyrics Analysis'), ('full', 'Full Analysis')], max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('acrcloud_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('cover', 'Cover Song'), ('similar', 'Similar Song'), ('no_match', 'No Match')], default='no_match', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Overall confidence score (0-100)', null=True)),
                ('fingerprint_matches', models.JSONField(blank=True, default=list)),
                ('fingerprint_score', models.FloatField(blank=True, null=True)),
                ('fingerprint_similarity', models.FloatField(blank=True, null=True)),
                ('cover_matches', models.JSONField(blank=True, default=list)),
                ('cover_score', models.FloatField(blank=True, null=True)),
                ('cover_similarity', models.FloatField(blank=True, null=True)),
                ('lyrics_matches', models.JSONField(blank=True, default=list)),
                ('lyrics_similarity', models.FloatField(blank=True, null=True)),
                ('detected_genre', models.CharField(blank=True, max_length=100)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('isrc_code', models.CharField(blank=True, max_length=12)),
                ('summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='acrcloud.analysis')),
            ],
            options={
                'verbose_name': 'Analysis Report',
                'verbose_name_plural': 'Analysis Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('audio_file', models.FileField(upload_to='acrcloud/songs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'flac', 'aac'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='acrcloud.song'),
        ),
    ]
