# Generated by Django 5.2.5 on 2025-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrcloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='detected_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='detected_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='isrc_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
