# Generated by Django 5.2.5 on 2025-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrcloud', '0003_webhooklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrcloudconfig',
            name='bearer_token',
            field=models.CharField(max_length=2000),
        ),
    ]
