# Generated by Django 5.2.5 on 2025-09-23 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrcloud', '0004_alter_acrcloudconfig_bearer_token'),
        ('soundcharts', '0019_album_acrcloud_id_album_musicbrainz_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACRCloudTrackMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('music', 'Music Match'), ('cover', 'Cover Song'), ('similar', 'Similar Song')], max_length=20)),
                ('acrcloud_id', models.CharField(max_length=255)),
                ('score', models.IntegerField(help_text='ACRCloud confidence score')),
                ('offset', models.FloatField(help_text='Match offset in seconds')),
                ('played_duration', models.FloatField(help_text='Duration of matched segment')),
                ('raw_data', models.JSONField(help_text='Complete ACRCloud match data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_matches', to='acrcloud.analysis')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soundcharts.track')),
            ],
            options={
                'verbose_name': 'ACRCloud Track Match',
                'verbose_name_plural': 'ACRCloud Track Matches',
                'ordering': ['-score', 'offset'],
                'indexes': [models.Index(fields=['analysis', 'match_type'], name='acrcloud_ac_analysi_3718ef_idx'), models.Index(fields=['score'], name='acrcloud_ac_score_bcc22d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformTrackMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_track_id', models.CharField(max_length=255)),
                ('platform_artist_id', models.CharField(blank=True, max_length=255)),
                ('platform_album_id', models.CharField(blank=True, max_length=255)),
                ('platform_url', models.URLField(blank=True)),
                ('platform_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundcharts.platform')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_mappings', to='soundcharts.track')),
            ],
            options={
                'verbose_name': 'Platform Track Mapping',
                'verbose_name_plural': 'Platform Track Mappings',
                'indexes': [models.Index(fields=['platform', 'platform_track_id'], name='acrcloud_pl_platfor_582750_idx')],
                'unique_together': {('track', 'platform', 'platform_track_id')},
            },
        ),
    ]
